### ISSUE TITLE
Segmentation fault on Linux 64

### ISSUE THREAD

**Issue by sdsddsd1** [ptitSeb/Serious-Engine#37]
Hello,
I am trying to get serious-engine running on my musl based box. The code is compiled with clang without problems. (Gcc11 failed btw).  
The menu starts up. However when starting the actual game, after the loading screen, it crashes with segmentation fault.
On a quick glance it looks related to https://github.com/ptitSeb/Serious-Engine/issues/20.  
I made a strace from the process, maybe this is helpful. Sry for not using an actual pastebin but the file is 16mb in size (: .
I made my own build script but it is identical with the build-linux64.sh  
```
cd Sources
cmake -B second \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

cd second
make ecc
make
```

[strace.txt](https://github.com/ptitSeb/Serious-Engine/files/6651959/strace.txt)

**Comment by ptitSeb** [comment]
Mmm, the freeze at the chain gun scene, I have seen this already. I have a fix for ARM 32 already in, it probably need to be extended to ARM64, I'll have to check.

**Comment by Trotter73** [comment]
Hi !

Cool, great stuff, if you need a tester I'm available... 

Ah OK, I must admit I didn't actually see a segfault, the Pi locked up fairly hard and I needed to pull the plug..

Thanks again !

**Comment by ptitSeb** [comment]
When I ported the game on the OpenPandora, I had some freeze issue due to some sin/cos table and some x86-isme in the code (like convert a NaN / infinite from float to int always gives 0x80000000, even for +inf). It should be fixed with some alternate version and some `#ifdef` in current code.

**Comment by SteffenHaeuser** [comment]
Thanks, this helped me a LOT! Actually it is #ifdef's for __arm__ in WorldCollisionGrid.cpp, TerrainMisc.cpp and Functions.h which needs to be 

#if defined(__arm__) || defined(__amigaos4__)

then it is fixed.

Though as if I saw right more people with other platforms have this issue maybe it should just be put in like that for ALL platforms, without ifdef ?

**Comment by SteffenHaeuser** [comment]
I think defining the original code only for x86/x86_64 sounds like a good idea actually. I saw this stuff with the chaingun crash in various issues on the issue tracker, I guess some could be closed after the fix.

**Comment by ptitSeb** [comment]
Done. Hopefully everything is working now?

**Comment by SteffenHaeuser** [comment]
Nearly all.
(1) Intro with the chain-gun -> working now
(2) Cathedral level in TSE -> working now
(3) TSE Intros on "new game" -> working now
(4) Hatshepsut Level started as multiplayer (singleplayer is no problem) IF installed with Gog data -> still crash (for CDROM version of the game it works on multiplayer fine)

I "solved" this by excluding this level from multiplayer if a specific file is present (the file is created by my installation script if the user selects "I install from Gog/Steam Data") - my installer works the way that the user has to provide the data either in form of a CD or as a directory with the data, and then everything is set up, and I did a little modification to the game source that it checks for this file and depending if it is present or not allows this specific multiplayer level or not (01_Hatshepshut).

I checked all levels, and all others are fine now.

**Comment by ptitSeb** [comment]
The Hatshepsut  issue is probably something else. maybe a missing updated file?

**Comment by SteffenHaeuser** [comment]
Possible. And as I said, at least from my point of view not so important. Especially as it works with some versions of the game and only some have the issue. I think we can close that issue here ?

**Comment by ptitSeb** [comment]
Yeah, I think ticket is done now.
